### PR TITLE
Reformatting and code fixes

### PR DESCRIPTION
**Pull request by rivimey**
Apologies for a mega-pull. I have tried to keep the individual commits distinct.

Overall,
 - some reformatting of the templates, which had got a bit random;
 - using t() more often;
 - follow suggestions to use __DIR__ in apache solr lib;
 - use 'template-php' (if... endif) in templates roughly in Drupal style;
 - simplify logic a lot;
 - add a couple of calls to htmlspecialchars() that seemed to be needed.

A few functional changes:
 - For list view use the filename if we have no title to avoid a page of 'no title';
 - Remove target=blank - makes navigation much harder than needed;
 - Fix search options button (for me at least wasn't working at all);
 - Fix sorting selector (ditto);

I am still unsure what to do about filenames/urls in general. relying on file: access doesn't work for me, so would like a mechanism to translate to e.g. specific http: on the server, or similar.

### CODE REVIEW

**Comment by opensemanticsearch** [comment]
Thank you very much. Will be merged after test tomorrow.

Please in future edit / pull request all files in directory src/Apache/Solr (i'll delete it from this repository) in https://github.com/opensemanticsearch/solr-php-client or if possible / accepted there directly in original repository https://github.com/PTCInc/solr-php-client

**Comment by Mandalka** [comment]
Opening files doesn't work because of browser security features. You can disable that blocking of opening file links for domains like your search engine.

**Comment by Mandalka** [comment]
Please do a git add, commit and push of app.js where the javascript was moved to by https://github.com/opensemanticsearch/solr-php-ui/pull/19/commits/1058fd25435eb6726a5bac24fb031c14d007f77f to close issue https://github.com/opensemanticsearch/solr-php-ui/issues/25

**Comment by opensemanticsearch** [comment]
One hint: If you do not want to allow your browser to open local files file:// from the website and setup a webserver, you can set a mapping in /etc/opensemanticsearch/connector-file, so the url is mapped from file://path to https://someurl/path in the index.

**Pull request merged**
