### PR TITLE
Add in missing appjs

### PR DESCRIPTION
**Pull request by rivimey**
Don't know why that happened; it wasn't showing as an uncommitted file but neither was it a file I created.
Anyway here it is.

### CODE REVIEW

**Comment by Mandalka** [comment]
Thank you very much!

**Comment by Mandalka** [comment]
The advanced search options are open yet even with the script, in your environment, too?

**Comment by Mandalka** [comment]
Full reload helps, sorry.

**Comment by rivimey** [comment]
Thanks... full reload helps: :)
Would you have a look at my branch rivimey/solr-php-ui/ruth/select_view ? I fixed the limit bug and the UL/SPAN issue earlier but hadn't done the PR for it yet!

**Comment by Mandalka** [comment]
Thanks, will append / change / merge (hope i can do it easy despite my changes at meantime) that to your more abstract and cleaner code later or tomorrow.

**Pull request merged**
